// <auto-generated />
using System;
using FBQ.Salud_AccessData.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FBQ.Salud_AccessData.Migrations
{
    [DbContext(typeof(FbqSaludDbContext))]
    partial class FbqSaludDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RolId")
                        .IsUnique();

                    b.ToTable("Admin");
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Rol", b =>
                {
                    b.Property<int>("RolId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RolId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RolId");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            RolId = 1,
                            Name = "Administrador"
                        },
                        new
                        {
                            RolId = 2,
                            Name = "Medico"
                        },
                        new
                        {
                            RolId = 3,
                            Name = "Recepcionista"
                        });
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<bool>("SoftDelete")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.HasIndex("RolId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DNI = "",
                            Email = "fbq.salud@gmail.com",
                            EmployeeId = 1,
                            FechaAlta = new DateTime(2024, 12, 7, 20, 54, 55, 140, DateTimeKind.Local).AddTicks(7382),
                            Password = "admin",
                            Picture = "claudio.jpg",
                            RolId = 1,
                            SoftDelete = false,
                            UserName = "admin"
                        },
                        new
                        {
                            UserId = 2,
                            DNI = "41389372",
                            Email = "marianocarrizo@gmail.com",
                            EmployeeId = 2,
                            FechaAlta = new DateTime(2024, 12, 7, 20, 54, 55, 140, DateTimeKind.Local).AddTicks(7392),
                            Password = "carrizo",
                            Picture = "foto.jpg",
                            RolId = 1,
                            SoftDelete = false,
                            UserName = "mariano"
                        },
                        new
                        {
                            UserId = 3,
                            DNI = "41389373",
                            Email = "medic@gmail.com",
                            EmployeeId = 3,
                            FechaAlta = new DateTime(2024, 12, 7, 20, 54, 55, 140, DateTimeKind.Local).AddTicks(7393),
                            Password = "medic",
                            Picture = "avatar-01.jpg",
                            RolId = 2,
                            SoftDelete = false,
                            UserName = "medico"
                        },
                        new
                        {
                            UserId = 4,
                            DNI = "41389376",
                            Email = "segundez@gmail.com",
                            EmployeeId = 4,
                            FechaAlta = new DateTime(2024, 12, 7, 20, 54, 55, 140, DateTimeKind.Local).AddTicks(7395),
                            Password = "segundo",
                            Picture = "avatar-05.jpg",
                            RolId = 2,
                            SoftDelete = false,
                            UserName = "segundez"
                        },
                        new
                        {
                            UserId = 5,
                            DNI = "41389379",
                            Email = "shrek@gmail.com",
                            EmployeeId = 5,
                            FechaAlta = new DateTime(2024, 12, 7, 20, 54, 55, 140, DateTimeKind.Local).AddTicks(7396),
                            Password = "tercero",
                            Picture = "avatar-03.jpg",
                            RolId = 2,
                            SoftDelete = false,
                            UserName = "tercerez"
                        },
                        new
                        {
                            UserId = 6,
                            DNI = "41389379",
                            Email = "krokotilde@gmail.com",
                            EmployeeId = 6,
                            FechaAlta = new DateTime(2024, 12, 7, 20, 54, 55, 140, DateTimeKind.Local).AddTicks(7397),
                            Password = "kotil",
                            Picture = "avatar-02.jpg",
                            RolId = 3,
                            SoftDelete = false,
                            UserName = "clotilde"
                        });
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Admin", b =>
                {
                    b.HasOne("FBQ.Salud_Domain.Entities.Rol", "Rol")
                        .WithOne("Admin")
                        .HasForeignKey("FBQ.Salud_Domain.Entities.Admin", "RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.User", b =>
                {
                    b.HasOne("FBQ.Salud_Domain.Entities.Rol", "Rol")
                        .WithMany("Users")
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("FBQ.Salud_Domain.Entities.Rol", b =>
                {
                    b.Navigation("Admin")
                        .IsRequired();

                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
